# Generated by Django 4.0.1 on 2022-01-24 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_gastos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='despesas',
            options={'verbose_name': 'Despesa', 'verbose_name_plural': 'Despesas'},
        ),
        migrations.AlterModelOptions(
            name='receitas',
            options={'verbose_name': 'Receita', 'verbose_name_plural': 'Receitas'},
        ),
        migrations.AddField(
            model_name='despesas',
            name='categoria',
            field=models.CharField(choices=[('A', 'Alimentação'), ('S', 'Saúde'), ('M', 'Moradia'), ('T', 'Transporte'), ('E', 'Educação'), ('L', 'Lazer'), ('I', 'Imprevisto'), ('O', 'Outro')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='despesas',
            name='data',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='despesas',
            name='descricao',
            field=models.CharField(max_length=120, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='despesas',
            name='valor',
            field=models.FloatField(verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='data',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='descricao',
            field=models.CharField(max_length=120, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='valor',
            field=models.FloatField(verbose_name='Valor'),
        ),
    ]
