# Generated by Django 4.0.1 on 2022-01-26 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_gastos', '0002_alter_despesas_options_alter_receitas_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesas',
            name='categoria',
            field=models.CharField(choices=[('A', 'Alimentação'), ('S', 'Saúde'), ('M', 'Moradia'), ('T', 'Transporte'), ('E', 'Educação'), ('L', 'Lazer'), ('I', 'Imprevisto'), ('O', 'Outro')], default='O', max_length=1, verbose_name='Categoria'),
        ),
    ]
